services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r ../food_project/requirements.txt"
    startCommand: "gunicorn config.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.8.4"